name: Bug Report
description: Report a bug with the AWX MCP Server
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Send JSON-RPC request: ...
        2. Observe error: ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include error messages or JSON-RPC responses if applicable.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Docker image tag
      description: Which version of the MCP server are you running?
      placeholder: "e.g. latest, v1.0.0, dev"
    validations:
      required: true
  - type: dropdown
    id: transport
    attributes:
      label: How are you running the server?
      options:
        - Docker (Claude Code / VS Code)
        - Docker (manual stdio)
        - Local Python
    validations:
      required: true
